# gen_manifest.py
from pathlib import Path
import json

IMG_DIR = Path("images")
DEST_JSON = IMG_DIR / "manifest.json"
DEST_JS   = IMG_DIR / "manifest.js"
EXTS = {".jpg", ".jpeg", ".png", ".webp", ".gif"}  # add more if needed

def main():
    files = []
    for p in sorted(IMG_DIR.iterdir()):
        if p.is_file() and p.suffix.lower() in EXTS and p.name not in {"manifest.json", "manifest.js"}:
            files.append(p.name)

    # JSON for normal HTTP(S) hosting
    DEST_JSON.write_text(json.dumps(files, indent=2), encoding="utf-8")

    # JS for file:// testing (assigns to a global)
    js = (
        "// Autogenerated by gen_manifest.py\n"
        "window.LOCAL_IMAGE_MANIFEST = " + json.dumps(files, indent=2) + ";\n"
    )
    DEST_JS.write_text(js, encoding="utf-8")

    print(f"Wrote {len(files)} entries to {DEST_JSON} and {DEST_JS}")

if __name__ == "__main__":
    main()
